# If you just need a quick backend for your Symfony application, this is the
# only configuration you must define in this file:
#
# spaceland:
#     entities:
#         - AppBundle\Entity\Variety
#         - AppBundle\Entity\Plant
#         - AppBundle\Entity\Purchase
#         - AppBundle\Entity\PurchaseItem
#         - AppBundle\Entity\Gardener
#
# In this demo application, the configuration is split into several small files
# to show an alternative way to define the configuration for complex backends.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://symfony.com/doc/current/bundles/EasyAdminBundle/index.html
#
imports:
    - { resource: spaceland/ }
